znetworkconfiguration:
  panid: 9945
  extendedpanid: 5149013381575969
  networkkey: [0x01, 0x03, 0x05, 0x07, 0x09, 0x0B, 0x0D, 0x0F, 0x00, 0x02, 0x04, 0x06, 0x08, 0x0A, 0x0C, 0x0D]
  channel: 26

mqttconfiguration:
  address: "192.168.1.25"
  port:    1883
  topic:   "gigbee2mqtt"

serialconfiguration:
  portname: "/dev/ttyACM0"
  baudrate: 115200

permitjoin: true